print()
print('Noun: Thing or person.')
print('Verb: Action or state.')
print('Adverb: Describes a verb, adjective, or adverb.')
print('Adjective: Describes a noun.')
print()
print('Please enter the following:')
print()
adjective1 = input('adjective: ')
adjective2 =input('adjective: ')
animal = input('animal: ')
food = input('plural food: ')
noun = input ('plural noun: ')
exclamation = input('exclamation: ')
verb1 = input('verb: ')
verb2 = input('verb: ')
verb3 = input('verb: ')
verb4 = input('verb: ')
adverb = input('adverb: ')
car = input('type of car: ')
print()
print('Your story is:')
print()
print(f'The other day, I was really in trouble. It all started when I saw a very')
print(f'{adjective1} {animal} {verb1} down the hallway while I was eating 5 tubs of')
print(f'{food}. "{exclamation.capitalize()}!" I yelled, accidentally droping my {food}')
print(f'on grandma. Angrily, grandma started throwing {noun} at me. All I could think')
print(f'to do was recklessly {verb2} over and over. After my sudden outburst, I decided')
print(f'to calmly {verb3}. Miraculously, that caused grandma and the {animal} to stop,')
print(f'but not before the {animal} tried to shamelessly {verb4} right in front of my')
print(f'family. Even after the sudden {animal} surprise and grandma attacking me, my family')
print(f'still had the audacity to {adverb} ask me why I was eating 5 tubs of {food}.')
print(f'Looking extremely {adjective2}, I stormed out of the building and drove away in my')
print(f'{car} because NO ONE tells me what I can or cannot eat.')
print()